# Generated by Django 5.2.3 on 2025-06-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountaddress',
            options={'verbose_name_plural': 'Account Addresses'},
        ),
        migrations.AlterModelOptions(
            name='accountbank',
            options={'verbose_name_plural': 'Account Banks'},
        ),
        migrations.AlterModelOptions(
            name='accountcategory',
            options={'verbose_name_plural': 'Account Categories'},
        ),
        migrations.AlterModelOptions(
            name='accountpic',
            options={'verbose_name_plural': 'Account PICs'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name_plural': 'Account Types'},
        ),
        migrations.AlterModelOptions(
            name='bankcategory',
            options={'verbose_name_plural': 'Bank Categories'},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='typeofbusiness',
            options={'verbose_name_plural': 'Type of Busineses'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='type_of_business_desc',
        ),
        migrations.AddField(
            model_name='accountbank',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
