# Generated by Django 5.2.3 on 2025-06-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_industry_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
