# Generated by Django 5.2.3 on 2025-06-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_accounttype_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttype',
            name='account_no',
        ),
        migrations.AddField(
            model_name='account',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
